#ifndef TECNA_GUI_DEF_H
#define TECNA_GUI_DEF_H

#define TEC_CMD_SCAN_MODULE_MAC_STN    "SLAVE SEND ACK"
#define TEC_CMD_DEVDISCOVERED_STN      "DEVICE DISCOVERED"
#define TEC_CMD_WARN_TO_SET_STN        "WARN TO SET MESSAGE"
#define TEC_CMD_PROT_ERR_STN           "THIS IS NOT TECNA PROTOCOL"
#define TEC_CMD_PROT_MASTER_STN        "THIS MESSAGE CAMES FROM MASTER"
#define TEC_CMD_SCAN_MODULE_STN        "MODULE SCAN"            // Not translateble
#define TEC_CMD_WARN_CODE_RCVD_STN     "SLAVE SEND CODE TO SET"


#endif // TECNA_GUI_DEF_H
