#ifndef TECNA_GUI_DEF_H
#define TECNA_GUI_DEF_H

#define TEC_CMD_SCAN_MODULE_MAC_STN         "SLAVE SEND ACK"
#define TEC_CMD_DEVDISCOVERED_STN           "DEVICE DISCOVERED"
#define TEC_CMD_WARN_TO_SET_STN             "WARN TO SET MESSAGE"
#define TEC_CMD_PROT_ERR_STN                "THIS IS NOT TECNA PROTOCOL"
#define TEC_CMD_PROT_SLAVE_STN              "THIS MESSAGE CAMES FROM THIS SLAVE"
#define TEC_CMD_SCAN_MODULE_STN             "MODULE SCAN"            // Not translateble
#define TEC_PROT_SLAVE_RX_INFO_STN          "SLAVE RECEIVED SCAN REQUEST"
#define TEC_PROT_SLAVE_RX_INFO_NACK_STN     "SLAVE RECEIVED WRONG MESSAGE"
#define TEC_PROT_SLAVE_RX_WARN_STN          "SLAVE RECEIVED WARN REQUEST"
#define TEC_PROT_SLAVE_RX_SET_STN           "SLAVE RECEIVED SET REQUEST"
#define TEC_PROT_SLAVE_HMS_STN              "SLAVE IS AN HMS DEVICE"


#endif // TECNA_GUI_DEF_H
